version: '2'

services:
  consul:
    command: -server -bootstrap -rejoin
    image: progrium/consul:latest
    hostname: "registry"
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  micro:
    command: --registry_address=consul:8500 web
    image: microhq/micro:latest
    links:
      - consul
      - user-service
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      MICRO_REGISTRY: "consul"

  user-service:
    command: --registry_address=consul:8500
    image: user-service:latest
    depends_on:
      - consul
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "consul"
